#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/mkan/Documents/GitHub/s-m_microp_project/fpga/weird_instrument_fpga/source}]} {
  file mkdir {C:/Users/mkan/Documents/GitHub/s-m_microp_project/fpga/weird_instrument_fpga/source}
}
cd {C:/Users/mkan/Documents/GitHub/s-m_microp_project/fpga/weird_instrument_fpga/source}

sys_set_attribute -gui on -msg {C:/Users/mkan/Documents/GitHub/s-m_microp_project/fpga/weird_instrument_fpga/promote.xml}
msg_load {C:/Users/mkan/Documents/GitHub/s-m_microp_project/fpga/weird_instrument_fpga/promote.xml}
des_set_project_udb -in {weird_instrument_fpga_source_syn.udb} -out {weird_instrument_fpga_source_map.udb} -milestone map -pm ice40tp
des_set_reference_udb -clean
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
